### ISSUE TITLE
Please add a screen shot and a license file

### ISSUE THREAD

**Issue by unixorn** [Rainrider/kudaranai.zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots in the readme so that users can see what they look like without having to install them.

Also, please add a license file, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

Thanks!

**Comment by Rainrider** [comment]
I actually have a license. I don't feel like making a readme with a screenshot right now but here is a screen just for you.

![Untitled](https://user-images.githubusercontent.com/363876/97498337-4cc3e100-196c-11eb-94fb-e987050870d9.png)

**Comment by unixorn** [comment]
Ok. Let me know when you add the license and I'll add it to the list, or you can PR it in yourself. Whatever is more convenient for you.
